### ISSUE TITLE
Iteration 4: Deployment Diagram

### ISSUE THREAD

**Issue by JulyJun** [mgrist/CS4306-PrincipalLED#17]
[description](https://www.conceptdraw.com/How-To-Guide/diagrams-software-tools-for-design-uml-deployment-diagram
![1](https://user-images.githubusercontent.com/41910139/142804313-8cc837ae-af7a-4bd4-a1a9-53d0e91a48fe.png)
)

**Comment by mgrist** [comment]
protocol

**Comment by JulyJun** [comment]
![1](https://user-images.githubusercontent.com/41910139/142804708-fe5e0af0-03bb-404c-be6b-aa5493472c9b.png)

**Comment by JulyJun** [comment]
[Link](https://drive.google.com/file/d/1Rnb6emo1eQB98mnvjoz_JibNET7AuBWR/view?usp=sharing)
